name:                url-shortener 
version:             0.1.0.0
github:              "githubuser/kek"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2021 Author name here"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/kek#readme>

dependencies:
- base >= 4.7 && < 5

# Database specific packages
- acid-state
- red-black-tree
- safecopy

# API specific packages
- servant
- aeson
- aeson-deriving
- servant-flatten

# Util
- mtl
- text

default-extensions:
  - DeriveDataTypeable
  - TemplateHaskell
  - TypeFamilies

library:
  ghc-options:
    #- -O3
    - -fwrite-ide-info
    - -hiedir=.hie
    - -Wall

  source-dirs: src

executables:
  shortener:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    #- -O3
    - -fwrite-ide-info
    - -hiedir=.hie
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    dependencies:
    - url-shortener

tests:
  shortener-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - url-shortener
